package au.lyrael.killall.utility;

import au.lyrael.killall.KillAll;
import cpw.mods.fml.common.ModMetadata;

public class MetadataHelper {
    public static ModMetadata transformMetadata(ModMetadata meta) {
        meta.authorList.clear();
        meta.authorList.add("LyraelRayne");
        meta.modId = KillAll.MOD_ID;
        meta.name = KillAll.MOD_NAME;
        meta.version = KillAll.VERSION;
        meta.description = KillAll.DESC;
        meta.url = KillAll.URL;
        meta.credits = KillAll.CREDITS;
        meta.logoFile = KillAll.LOGO_PATH;
        meta.autogenerated = false;
        return meta;
    }
}
